services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./prisma-app:/app
    tty: true
    environment:
      - WATCHPACK_POLLING=true
      # - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres
    command: npm run dev
  db:
    image: postgres:17-alpine
    container_name: prisma-app-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: